### ISSUE TITLE
Issue when executing example code

### ISSUE THREAD

**Issue by michaelfekadu** [flyconnectome/cocoa#2]
I encountered issues while attempting to run the example provided in the README file. Despite following all the steps outlined in both the 'install' and 'other requirements' sections, I faced an error upon executing the following code:

<img width="587" alt="Screenshot 2024-04-09 at 13 32 22" src="https://github.com/flyconnectome/cocoa/assets/116261208/b5946c39-cb07-4703-ae13-a98e117a47b1">

The error messages I received are shown below:

```
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
Cell In[20], [line 25](vscode-notebook-cell:?execution_count=20&line=25)
     [20](vscode-notebook-cell:?execution_count=20&line=20) fwr = cc.FlyWire(label='FlyWire_right',
     [21](vscode-notebook-cell:?execution_count=20&line=21)                 materialization=783,
     [22](vscode-notebook-cell:?execution_count=20&line=22)                 live_annot=False  # this make sure we use data from flytable
     [23](vscode-notebook-cell:?execution_count=20&line=23)                 ).add_neurons(['SLP001', 'SLP003'], sides='right')
     [24](vscode-notebook-cell:?execution_count=20&line=24) # # Combine into a clustering and co-cluster
---> [25](vscode-notebook-cell:?execution_count=20&line=25) cl = cc.Clustering([hb, fwl, fwr]).compile()
     [26](vscode-notebook-cell:?execution_count=20&line=26) # # The clustering `cl` contains the results of the clustering
     [27](vscode-notebook-cell:?execution_count=20&line=27) cl.dists_

File [/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/cocoa/cluster.py:256](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/cocoa/cluster.py:256), in Clustering.compile(self, join, metric, force_recompile, exclude_labels, include_labels, cn_frac_threshold, augment, verbose)
    [250](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/cocoa/cluster.py:250)     if not hasattr(ds, "edges_") or force_recompile:
    [251](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/cocoa/cluster.py:251)         printv(
    [252](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/cocoa/cluster.py:252)             f'Compiling connectivity vector for "{ds.label}" '
    [253](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/cocoa/cluster.py:253)             f"({ds.type}) [{i+1}[/](https://file+.vscode-resource.vscode-cdn.net/){len(self.datasets)}]",
    [254](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/cocoa/cluster.py:254)             verbose=verbose,
    [255](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/cocoa/cluster.py:255)         )
--> [256](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/cocoa/cluster.py:256)         ds.compile()
    [258](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/cocoa/cluster.py:258) # Extract labels
    [259](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/cocoa/cluster.py:259) all_labels = set()

File [/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/cocoa/datasets/flywire.py:244](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/cocoa/datasets/flywire.py:244), in FlyWire.compile(self)
    [242](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/cocoa/datasets/flywire.py:242) else:
    [243](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/cocoa/datasets/flywire.py:243)     if self.upstream:
--> [244](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/cocoa/datasets/flywire.py:244)         us = flywire.get_connectivity(
    [245](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/cocoa/datasets/flywire.py:245)             x,
    [246](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/cocoa/datasets/flywire.py:246)             upstream=True,
    [247](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/cocoa/datasets/flywire.py:247)             downstream=False,
    [248](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/cocoa/datasets/flywire.py:248)             proofread_only=True,
    [249](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/cocoa/datasets/flywire.py:249)             filtered=True,
    [250](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/cocoa/datasets/flywire.py:250)             min_score=50,
    [251](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/cocoa/datasets/flywire.py:251)             progress=False,
    [252](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/cocoa/datasets/flywire.py:252)             materialization=mat,
    [253](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/cocoa/datasets/flywire.py:253)         )
    [254](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/cocoa/datasets/flywire.py:254)     if self.downstream:
    [255](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/cocoa/datasets/flywire.py:255)         ds = flywire.get_connectivity(
    [256](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/cocoa/datasets/flywire.py:256)             x,
    [257](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/cocoa/datasets/flywire.py:257)             upstream=False,
   (...)
    [263](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/cocoa/datasets/flywire.py:263)             materialization=mat,
    [264](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/cocoa/datasets/flywire.py:264)         )

File [/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/fafbseg/flywire/annotations.py:128](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/fafbseg/flywire/annotations.py:128), in parse_neuroncriteria.<locals>.outer.<locals>.inner(*args, **kwargs)
    [126](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/fafbseg/flywire/annotations.py:126)         kwargs[key] = nc.get_roots()
    [127](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/fafbseg/flywire/annotations.py:127) try:
--> [128](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/fafbseg/flywire/annotations.py:128)     return func(*args, **kwargs)
    [129](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/fafbseg/flywire/annotations.py:129) except NoMatchesError as e:
    [130](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/fafbseg/flywire/annotations.py:130)     if allow_empty:

File [/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/fafbseg/flywire/utils.py:167](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/fafbseg/flywire/utils.py:167), in inject_dataset.<locals>.outer.<locals>.inner(*args, **kwargs)
    [165](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/fafbseg/flywire/utils.py:165) if disallowed and ds in disallowed:
    [166](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/fafbseg/flywire/utils.py:166)     raise ValueError(f'Dataset "{ds}" not allowed for function {func}.')
--> [167](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/fafbseg/flywire/utils.py:167) return func(*args, **kwargs)

File [/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/fafbseg/flywire/synapses.py:1263](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/fafbseg/flywire/synapses.py:1263), in get_connectivity(x, clean, style, upstream, downstream, proofread_only, transmitters, neuropils, filtered, min_score, batch_size, materialization, progress, dataset)
   [1261](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/fafbseg/flywire/synapses.py:1261) if proofread_only:
   [1262](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/fafbseg/flywire/synapses.py:1262)     all_ids = np.unique(cn_table[["pre", "post"]].values.flatten())
-> [1263](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/fafbseg/flywire/synapses.py:1263)     is_pr = all_ids[is_proofread(all_ids, materialization=materialization)]
   [1265](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/fafbseg/flywire/synapses.py:1265)     # Make sure we don't drop our query neurons
   [1266](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/fafbseg/flywire/synapses.py:1266)     keep = np.append(is_pr, ids)

File [/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/fafbseg/flywire/utils.py:167](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/fafbseg/flywire/utils.py:167), in inject_dataset.<locals>.outer.<locals>.inner(*args, **kwargs)
    [165](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/fafbseg/flywire/utils.py:165) if disallowed and ds in disallowed:
    [166](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/fafbseg/flywire/utils.py:166)     raise ValueError(f'Dataset "{ds}" not allowed for function {func}.')
--> [167](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/fafbseg/flywire/utils.py:167) return func(*args, **kwargs)

File [/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/fafbseg/flywire/annotations.py:202](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/fafbseg/flywire/annotations.py:202), in is_proofread(x, materialization, cache, validate, dataset)
    [200](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/fafbseg/flywire/annotations.py:200)         table = PR_TABLE[materialization]
    [201](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/fafbseg/flywire/annotations.py:201)     else:
--> [202](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/fafbseg/flywire/annotations.py:202)         table = client.materialize.query_table(table='proofreading_status_public_v1',
    [203](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/fafbseg/flywire/annotations.py:203)                                                materialization_version=materialization)
    [204](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/fafbseg/flywire/annotations.py:204)         PR_TABLE[materialization] = table
    [205](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/fafbseg/flywire/annotations.py:205) else:

File [/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/caveclient/materializationengine.py:742](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/caveclient/materializationengine.py:742), in MaterializatonClientV2.query_table(self, table, filter_in_dict, filter_out_dict, filter_equal_dict, filter_spatial_dict, filter_regex_dict, select_columns, offset, limit, datastack_name, return_df, split_positions, materialization_version, timestamp, metadata, merge_reference, desired_resolution, get_counts, random_sample)
    [733](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/caveclient/materializationengine.py:733) headers = {"Content-Type": "application/json", "Accept-Encoding": encoding}
    [735](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/caveclient/materializationengine.py:735) response = self.session.post(
    [736](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/caveclient/materializationengine.py:736)     url,
    [737](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/caveclient/materializationengine.py:737)     data=json.dumps(data, cls=BaseEncoder),
   (...)
    [740](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/caveclient/materializationengine.py:740)     stream=~return_df,
    [741](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/caveclient/materializationengine.py:741) )
--> [742](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/caveclient/materializationengine.py:742) self.raise_for_status(response)
    [743](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/caveclient/materializationengine.py:743) if return_df:
    [744](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/caveclient/materializationengine.py:744)     with warnings.catch_warnings():

File [/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/caveclient/base.py:226](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/caveclient/base.py:226), in ClientBase.raise_for_status(r, log_warning)
    [222](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/caveclient/base.py:222) @staticmethod
    [223](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/caveclient/base.py:223) def raise_for_status(r, log_warning=True):
    [224](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/caveclient/base.py:224)     """Raises :class:`HTTPError`, if one occurred."""
--> [226](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/caveclient/base.py:226)     _raise_for_status(r, log_warning=log_warning)

File [/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/caveclient/base.py:79](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/caveclient/base.py:79), in _raise_for_status(r, log_warning)
     [71](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/caveclient/base.py:71)     http_error_msg = "%s Server Error: %s for url: %s content:%s" % (
     [72](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/caveclient/base.py:72)         r.status_code,
     [73](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/caveclient/base.py:73)         reason,
     [74](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/caveclient/base.py:74)         r.url,
     [75](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/caveclient/base.py:75)         r.content,
     [76](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/caveclient/base.py:76)     )
     [78](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/caveclient/base.py:78) if http_error_msg:
---> [79](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/caveclient/base.py:79)     raise requests.HTTPError(http_error_msg, response=r)
     [80](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/caveclient/base.py:80) if log_warning:
     [81](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/compcon/lib/python3.9/site-packages/caveclient/base.py:81)     warning = r.headers.get("Warning")

HTTPError: 500 Server Error: 404 Not Found: analysis table proofreading_status_public_v1 not found for version 783 in datastack flywire_fafb_public for url: https://prod.flywire-daf.com/materialize/api/v3/datastack/flywire_fafb_public/version/783/table/proofreading_status_public_v1/query?return_pyarrow=True&arrow_format=True&split_positions=True content:b'{"code": 500, "message": "404 Not Found: analysis table proofreading_status_public_v1 not found for version 783 in datastack flywire_fafb_public", "traceback": ["Traceback (most recent call last):\\n", "  File \\"/usr/local/lib/python3.9/site-packages/flask/app.py\\", line 1516, in full_dispatch_request\\n    rv = self.dispatch_request()\\n", "  File \\"/usr/local/lib/python3.9/site-packages/flask/app.py\\", line 1502, in dispatch_request\\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\\n", "  File \\"/usr/local/lib/python3.9/site-packages/flask_restx/api.py\\", line 403, in wrapper\\n    resp = resource(*args, **kwargs)\\n", "  File \\"/usr/local/lib/python3.9/site-packages/flask/views.py\\", line 84, in view\\n    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)\\n", "  File \\"/usr/local/lib/python3.9/site-packages/flask_restx/resource.py\\", line 49, in dispatch_request\\n    resp = meth(*args, **kwargs)\\n", "  File \\"/app/./materializationengine/blueprints/reset_auth.py\\", line 12, in decorated_function\\n    return f(*args, **kwargs)\\n", "  File \\"/usr/local/lib/python3.9/site-packages/middle_auth_client/decorators.py\\", line 265, in decorated_function\\n    return f(*args, **kwargs)\\n", "  File \\"/usr/local/lib/python3.9/site-packages/middle_auth_client/decorators.py\\", line 396, in decorated_function\\n    return f(*args, **kwargs)\\n", "  File \\"/usr/local/lib/python3.9/site-packages/flask_limiter/extension.py\\", line 1186, in __inner\\n    R, flask.current_app.ensure_sync(cast(Callable[P, R], obj))(*a, **k)\\n", "  File \\"/app/./materializationengine/blueprints/client/datastack.py\\", line 70, in wrapper\\n    return f(*args, **kwargs)\\n", "  File \\"/usr/local/lib/python3.9/site-packages/flask_accepts/decorators/decorators.py\\", line 206, in inner\\n    return func(*args, **kwargs)\\n", "  File \\"/app/./materializationengine/blueprints/client/api2.py\\", line 889, in post\\n    return handle_simple_query(\\n", "  File \\"/app/./materializationengine/blueprints/client/common.py\\", line 197, in handle_simple_query\\n    validate_table_args([table_name], target_datastack, target_version)\\n", "  File \\"/app/./materializationengine/blueprints/client/common.py\\", line 181, in validate_table_args\\n    abort(\\n", "  File \\"/usr/local/lib/python3.9/site-packages/werkzeug/exceptions.py\\", line 940, in abort\\n    _aborter(status, *args, **kwargs)\\n", "  File \\"/usr/local/lib/python3.9/site-packages/werkzeug/exceptions.py\\", line 923, in __call__\\n    raise self.mapping[code](*args, **kwargs)\\n", "werkzeug.exceptions.NotFound: 404 Not Found: analysis table proofreading_status_public_v1 not found for version 783 in datastack flywire_fafb_public\\n"]}\n'```

**Comment by schlegelp** [comment]
Hi! The error is truncated (try clicking on "View as scrollable element") but I suspect that it originates from the `fafbseg` package. Not sure what version of `fafbseg` you have installed but I do remember an issue along the lines of this error message in the recent. Could you update fafbseg and try again just to make sure this isn't already solved in the current version:

```sh
pip install fafbseg -U
```

**Comment by michaelfekadu** [comment]
Hi @schlegelp, thank you for your prompt response. I've made some edits to my issue post and included the complete error message. Could you please take a look? Additionally, I attempted to update fafbseg, but unfortunately, I'm still encountering the same error message. The version of fafbseg I'm currently using is 3.0.6.

**Comment by schlegelp** [comment]
OK, that's odd. Can you share the output of running this in the same Python session were you get the error:
```python
import fafbseg
print(fafbseg.__version__)
```

**Comment by michaelfekadu** [comment]
I forgot to restart the kernel. It's working now. Thank you so much!
